{% set name = "plotlydash-tornado-cmd" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af508a04b6a38e03dc9add58c019ce0407b01c9053a850bd4c6c6a049f64bfaf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - plotlydash-tornado-cmd = plotlydash_tornado_cmd.main:run

requirements:
  host:
    - python >=3.6,<4.0.0
    - pip
  run:
    - python >=3.6,<4.0.0
    - tornado >=5.0
    - click >=7.0

test:
  imports:
    - plotlydash_tornado_cmd      
  requires:
    - pip
  commands:
    - pip check
    - plotlydash-tornado-cmd --help

about:
  home: https://github.com/ideonate/plotlydash-tornado-cmd
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Command line wrapper to run a named Plotly Dash script inside a Tornado server
  dev_url: https://github.com/ideonate/plotlydash-tornado-cmd

extra:
  recipe-maintainers:
    - danlester
    - fcollonval
